package forward;
import  com.ftn.sbnz.model.models.Car;
import com.ftn.sbnz.model.events.Filter1;
import com.ftn.sbnz.model.events.Filter2;

import java.util.ArrayList;
import java.util.List;

global String makeFilter;
global String modelFilter;
global Integer hpFilter;
global List<Car> filteredCars;

rule "Filter by make"
when
    $car: Car(make==makeFilter)
then
    insert(new Filter1($car));
end


rule "Filter by model"
when
    $filter : Filter1($car : car, $car.model == modelFilter)
then
    retract($filter)
    insert(new Filter2($car));
end

rule "Filter by HP"
when
    $filter : Filter2($car : car, $car.engineHp >= hpFilter)
then
    retract($filter)
    filteredCars.add($car);
end